---

- name: spring nutrition provisionning
  hosts: nutrition
  become: yes

  pre_tasks : 
    - name: ensure unzip is installed
      apt: name="unzip" state="present"
    - name: adding fake hostname
      lineinfile:
        dest:  /etc/hosts
        regexp: '^192\.168\.5\.5*'
        line: "192.168.5.5 medidoc.vm"
  roles: 
    - role : ansible-role-mysql
      mysql_root_password: "verycomplicatedrootpassword"
      mysql_users:
        - name: nutrition
          host: "%"
          password: nutrition
          priv: "medidoc.*:ALL"
      mysql_databases:
        - name: medidoc
          collation: utf8_general_ci
          encoding: utf8
    - role: tomcat_role
    - role: apache2
      servername: medidoc.vm
      serveradmin: abderrahmane
      appname: medidoc

      

