# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"



  config.vm.define "nutrition" do |nutrition|

        #                          Vagrant machine                             #

        nutrition.vm.hostname = "nutrition.vm"
        nutrition.vm.network :private_network, ip: "192.168.5.5"

        #                             VirtualBox                               #

        nutrition.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--memory", 1024]
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.name = "nutrition"
        end
        nutrition.vm.provision "shell",
          inline: "sudo apt-get -y install python"
        nutrition.vm.provision "ansible" do |ansible|
          ansible.playbook = "nutrition.yml"
          ansible.groups = {
            "sonar" => ["default"]
          }
        ansible.verbose = "v"
#        ansible.ask_vault_pass = true
        end
  end
end

